### ISSUE TITLE
Feature: User can pick a day for date 

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can pick a day for the date

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be answering a form with their desired day, month and year from a dropdown option.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![datedesk](https://user-images.githubusercontent.com/76453386/119411149-cb80c280-bc9e-11eb-8707-4c96f4cc1521.png)
![date](https://user-images.githubusercontent.com/76453386/119411284-0256d880-bc9f-11eb-947d-bf5a94e1e57b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component to create a NewDate form
   - [x] renders a form containing three inputs for 'Day'
      - [x] type 'dropdown' for day, month, year
   - [x] set state to keep track of 'Day' value
   - [x] create method that checks day to determine day of the week
     - [x] return corresponding day of the week and day
   - [x] attach onChange prop to input month
      - [x] update days list to include correct day of the week
- [x] Create 'Date' title for form
- [x] Center form on page
- [x] Adjust sizing, font, color

### 🧑‍⚕️ Clean Up
 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
