### ISSUE TITLE
Feature: User can set a time for date

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set a time for date

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will have an input to type in desired time and a drop down to select am / pm

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![time](https://user-images.githubusercontent.com/76453386/119551628-b2cfe580-bd4e-11eb-8f1e-588d555cdfdd.png)
![time2](https://user-images.githubusercontent.com/76453386/119551630-b3687c00-bd4e-11eb-8f32-78561b9e2940.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component that renders 2 inputs for Time
   - [x] Create label for 'Time' input
   - [x] Create input with type 'time'
- [x] Add Time component to DataForm component
- [x] Style Elements

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
