### ISSUE TITLE
Feature: User can set activity

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set activity

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to choose an activity from a dropdown menu. Each activity will have an assigned color

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ac](https://user-images.githubusercontent.com/76453386/119581531-998f5f00-bd77-11eb-9a19-20455bfd00e2.png)
![ax](https://user-images.githubusercontent.com/76453386/119581532-998f5f00-bd77-11eb-8cf1-b6ee16aaece7.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a component InputActivity
   - [x] create input type dropdown
   - [x] map through array of activities to render options
- [x] Update DateForm component 
   - [x] to have activities array
   - [x] to save selectedActivity
   - [x] to include Input Activity component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
