### ISSUE TITLE
Feature: User can set the location for date

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can set the location for date
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the location input is clicked, a pop-up will appear with the search bar filled out with the preset activity, user can change searches and select the desired location
![loc](https://user-images.githubusercontent.com/76453386/119723082-e9c2fb80-be21-11eb-8419-05e6dc59e0cc.png)
![loc2](https://user-images.githubusercontent.com/76453386/119723086-ea5b9200-be21-11eb-857c-a86420243a66.png)

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to fetch places from API
- [x] Check API by fetching in browser 
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Update DateForm component to have a location search bar
- [x] Create a GetPlaces component that 
   - [x] accepts keyword from selected activity
   - [x] renders places using a search keyword
      - [x] List of places is a pop-up with
         - [x] Name
         - [x] Rating
         - [x] Address
         - [x] 'Set' button that 
            - [x] saves the address of the chosen location 
            - [x] displays address on dateform search bar

### 🧑‍⚕️ Clean Up

- [ ] 
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
