### ISSUE TITLE
Feature: User can invite contacts

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can invite contacts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click on a contact input and a contacts list will pop-up. An add button will be available and an 'Add Contact' Form will show when click clicked.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![contactdesk](https://user-images.githubusercontent.com/76453386/120031244-67ffd900-bfad-11eb-8a01-73ce43a079a0.png)
![contacts](https://user-images.githubusercontent.com/76453386/120031246-68986f80-bfad-11eb-8edb-f0fb246a173e.png)
![contacts2](https://user-images.githubusercontent.com/76453386/120031248-68986f80-bfad-11eb-9fda-e6791a7e26c6.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to 
   - [x] create 'public' schema
   - [x] create 'user' table with categories
      - [x] UserId, Name, Phone#, FriendId
    - [x] create 'contacts' table with categories
       - [x] UserID, Name, Phone#, FriendId
    - [x] create 'Date' table with categories
       - [x] UserId, DateId Location, Day, Time, Activity, Notes
- [x] Update `data.sql` to insert 
   - [x] tester user
   - [x] contacts
   - [x] date

### ☁️ Server

- [x] Update `server/index.js` to get 'api/contacts'
- [x] Update `server/index.js` to get 'api/date'
- [x] Update `server/index.js` to post 'api/date'
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create an 'Add Invites' component that
   - [x] renders add contacts input
   - [x] shows 'Contacts' modal 
      - [x] renders list of contacts
      - [x] has an add button
        - [x] renders contact form modal on click
           - [x] contains inputs Name, Number & Image
           - [x] contains add / cancel button
 - [x] Create 'accept/cancel' component
 - [x] contains 2 buttons
    - [x] Invite
       - [x] creates post request to server
    - [x] Cancel
       - [x] deletes all inputs
       - [x] goes back to 'home screen'
- [x] Update DateForm component to 
   - [x] render 'Add Invites' component
   - [x] have a textarea input
   - [x] render accept/cancel component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
