### ISSUE TITLE
Feature: User can see colored dates on calendar

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can see colored dates on calendar

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A calendar with a monthly view will be shown on the home screen. If there is a scheduled date on a certain day, the calendar will be marked on that day with a bubble with an assigned color.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2021-06-02 210754](https://user-images.githubusercontent.com/76453386/120585489-b0bcf500-c3e6-11eb-8cc8-a934707a392b.png)
![Screenshot 2021-06-02 210818](https://user-images.githubusercontent.com/76453386/120585490-b1558b80-c3e6-11eb-91a5-d038b2a51c24.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create a Calendar component that
   - [x] has 7 day of the week
   - [x] shows all the days of the month
   - [x] updates the days of the month when month is switched
   - [x] has a color bubble if there is a date on that day
- [x] Update Home component to render the calendar

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
