### ISSUE TITLE
Feature: User can click on a date on calendar, calendar changes to weekly view

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

 User can click on a date on calendar
## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks on a day on the calendar, it will change to a different 'page' where the view is only the week clicked.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screenshot 2021-06-04 145035](https://user-images.githubusercontent.com/76453386/120866387-aca6e980-c544-11eb-8869-97ca7f514c8a.png)
![Screenshot 2021-06-04 145055](https://user-images.githubusercontent.com/76453386/120866388-aca6e980-c544-11eb-84a1-5fe08f4109a1.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create WeeklyView component that 
   - [x] onClick on a day, shows the days of that week
   - [x] onClick of the task icon, shows days of current week 
- [x] Update calendar component to save isSelected day
- [x] Update App component to have Weekly view

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
