### ISSUE TITLE
Feature: User can view daily schedule

### ISSUE THREAD

**Issue by mduguil** [mduguil/It-s-A-Date#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view daily schedule

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When a user clicks on a day on the calendar, the view will switch to weekly view and and the scheduled date will show in the form of a list below the week calendar.
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![sched](https://user-images.githubusercontent.com/76453386/121574570-3fc79f80-c9db-11eb-9853-47ee6178749d.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ⚡ Client

- [x] Create ShowDatesScheduled component that renders date
   - [x] Activity
   - [x] Location
   - [x] Time
   - [x] Invited Contact
- [x] Update WeeklyView component to include ShowDatesScheduled component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
